# -*- coding: utf-8 -*-
"""
gen_speed_font.py - Generate the big current-speed digit font (digits + '-').

Usage: python tools/fonts/gen_speed_font.py <px> [name]
  python tools/fonts/gen_speed_font.py 64 lv_font_montserrat_speed64   # VietHUD 2.8 (320x240)

Same Pillow-based approach and LVGL 9.2.2 fmt_txt constraints as
gen_vn_font.py (bpp=4 PLAIN, FORMAT0_TINY cmap): see that file's docstring.
The 92 px lv_font_montserrat_speed.c was produced by an earlier, uncommitted
variant of this generator; this one is the checked-in replacement.
"""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
TTF = os.path.join(ROOT, ".pio", "libdeps", "viethud", "lvgl", "scripts", "built_in_font", "Montserrat-Medium.ttf")
PPEM = int(sys.argv[1]) if len(sys.argv) > 1 else 64
NAME = sys.argv[2] if len(sys.argv) > 2 else "lv_font_montserrat_speed%d" % PPEM
OUT = os.path.join(ROOT, "src", "ui", "fonts", NAME + ".c")

font = ImageFont.truetype(TTF, PPEM)
ascent, descent = font.getmetrics()
line_height = ascent + descent
pad = PPEM + 4

# Two contiguous ranges: '-' (0x2D) and '0'..'9' (0x30..0x39)
RANGES = [("-",), tuple(chr(c) for c in range(0x30, 0x3A))]


def render(ch):
    adv_w = int(round(font.getlength(ch) * 16))
    img = Image.new("L", (int(font.getlength(ch)) + 2 * pad, line_height + 2 * pad), 0)
    base_y = pad + ascent
    ImageDraw.Draw(img).text((pad, base_y), ch, font=font, fill=255, anchor="ls")
    bbox = img.getbbox()
    if bbox is None:
        return 0, 0, 0, 0, adv_w, []
    l, t, r, b = bbox
    nibs = [(v * 15 + 127) // 255 for v in img.crop(bbox).getdata()]
    return r - l, b - t, l - pad, base_y - b, adv_w, nibs


bitmap = []
dsc = [(0, 0, 0, 0, 0, 0)]
for rng in RANGES:
    for ch in rng:
        bw, bh, ox, oy, aw, nibs = render(ch)
        idx = len(bitmap)
        for i in range(0, len(nibs), 2):
            lo = nibs[i + 1] if i + 1 < len(nibs) else 0
            bitmap.append(((nibs[i] & 0xF) << 4) | (lo & 0xF))
        dsc.append((idx, aw, bw, bh, ox, oy))

L = []
w = L.append
w("/******************************************************************************")
w(" * Size: %d px" % PPEM)
w(" * Bpp: 4")
w(" * Subset: '-' and '0'-'9' only")
w(" *")
w(" * GENERATED by tools/fonts/gen_speed_font.py -- do NOT hand-edit. Source:")
w(" * Montserrat-Medium.ttf from LVGL's scripts/built_in_font/.")
w(" ******************************************************************************/")
w("")
w("#ifdef LV_LVGL_H_INCLUDE_SIMPLE")
w('    #include "lvgl.h"')
w("#else")
w('    #include "lvgl/lvgl.h"')
w("#endif")
w("")
w("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {")
for i in range(0, len(bitmap), 16):
    w("    " + " ".join("0x%02x," % b for b in bitmap[i:i + 16]))
w("};")
w("")
w("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
for (bi, aw, bw, bh, ox, oy) in dsc:
    w("    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, .ofs_y = %d}," % (bi, aw, bw, bh, ox, oy))
w("};")
w("")
w("static const lv_font_fmt_txt_cmap_t cmaps[] = {")
gid = 1
for rng in RANGES:
    w("    {.range_start = %d, .range_length = %d, .glyph_id_start = %d, .unicode_list = NULL," % (ord(rng[0]), len(rng), gid))
    w("     .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},")
    gid += len(rng)
w("};")
w("")
w("static const lv_font_fmt_txt_dsc_t font_dsc = {")
w("    .glyph_bitmap = glyph_bitmap,")
w("    .glyph_dsc = glyph_dsc,")
w("    .cmaps = cmaps,")
w("    .kern_dsc = NULL,")
w("    .kern_scale = 0,")
w("    .cmap_num = %d," % len(RANGES))
w("    .bpp = 4,")
w("    .kern_classes = 0,")
w("    .bitmap_format = 0,")
w("};")
w("")
w("const lv_font_t %s = {" % NAME)
w("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,")
w("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
w("    .line_height = %d," % line_height)
w("    .base_line = %d," % descent)
w("    .subpx = LV_FONT_SUBPX_NONE,")
w("    .underline_position = 0,")
w("    .underline_thickness = 0,")
w("    .dsc = &font_dsc,")
w("};")
w("")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(L))
print("Wrote", OUT, "line_height", line_height, "bitmap bytes", len(bitmap))
