#!/usr/bin/env python3
"""
build_osm_signals.py — extract OpenStreetMap traffic signals (highway=traffic_signals)
for Vietnam and generate src/map/OsmTrafficSignals.cpp, a flash-resident table
the firmware merges into its traffic-light warnings at boot (SdCardManager.cpp).

Why built into the firmware: the WYN alert data has NO traffic lights in inner
Hanoi (bench audit 2026-09-27: 0 vs 364 signalized intersections in OSM), and
firmware OTA is the one channel that reaches every device. OSM coordinates are
real-world WGS84, so these points line up with the OSM road network the map
matcher uses.

Data: (c) OpenStreetMap contributors, ODbL 1.0 — https://www.openstreetmap.org/copyright

Usage:
    python build_osm_signals.py [vietnam-latest.osm.pbf] [out.cpp]
"""
import math
import sys
from pathlib import Path

import osmium

HERE = Path(__file__).resolve().parent
PBF = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "vietnam-latest.osm.pbf"
OUT = Path(sys.argv[2]) if len(sys.argv) > 2 else HERE.parent.parent / "src" / "map" / "OsmTrafficSignals.cpp"
DEDUP_M = 8.0  # the same signal mapped twice


class Signals(osmium.SimpleHandler):
    """Pass 1: signal nodes (+ traffic_signals:direction forward/backward)."""
    def __init__(self):
        super().__init__()
        self.nodes = {}  # id -> [latE7, lonE7, dirTag, bearing or None]

    def node(self, n):
        if n.tags.get("highway") == "traffic_signals" and n.location.valid():
            d = n.tags.get("traffic_signals:direction") or n.tags.get("direction")
            d = d if d in ("forward", "backward") else None
            self.nodes[n.id] = [round(n.location.lat * 1e7), round(n.location.lon * 1e7), d, None]


def bearing(a, b):
    kx = math.cos(math.radians(a.lat))
    return (math.degrees(math.atan2((b.lon - a.lon) * kx, b.lat - a.lat)) + 360.0) % 360.0


class WayDirs(osmium.SimpleHandler):
    """Pass 2: for a directed signal node, the travel direction it controls =
    bearing of the way segment the vehicle drives on while approaching it
    (forward = along the way's node order, backward = against it)."""
    def __init__(self, nodes):
        super().__init__()
        self.nodes = nodes

    def way(self, w):
        if "highway" not in w.tags:
            return
        nl = w.nodes
        for i in range(len(nl)):
            rec = self.nodes.get(nl[i].ref)
            if not rec or not rec[2] or rec[3] is not None:
                continue
            try:
                if rec[2] == "forward":
                    a, b = (nl[i - 1], nl[i]) if i > 0 else (nl[i], nl[i + 1])
                else:
                    a, b = (nl[i + 1], nl[i]) if i + 1 < len(nl) else (nl[i], nl[i - 1])
                if a.location.valid() and b.location.valid():
                    rec[3] = bearing(a.location, b.location)
            except IndexError:
                pass


def main():
    h = Signals()
    h.apply_file(str(PBF), locations=False)
    WayDirs(h.nodes).apply_file(str(PBF), locations=True, idx="flex_mem")
    pts = sorted({(la, lo, (round(b) % 360) if b is not None else 0xFFFF) for la, lo, _, b in h.nodes.values()})
    ndir = sum(1 for p in pts if p[2] != 0xFFFF)
    # drop near-duplicates (grid of ~DEDUP_M cells)
    keep, grid = [], {}
    cell = DEDUP_M / 110540 * 1e7
    for la, lo, dd in pts:
        gx, gy = int(la // cell), int(lo // cell)
        dup = False
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                for qa, qo, qd in grid.get((gx + dx, gy + dy), ()):
                    if qd == dd and math.hypot((la - qa) / 1e7 * 110540, (lo - qo) / 1e7 * 106000) < DEDUP_M:
                        dup = True
        if not dup:
            keep.append((la, lo, dd))
            grid.setdefault((gx, gy), []).append((la, lo, dd))
    keep.sort()  # by latitude (firmware merges then re-sorts anyway)
    lines = [
        "// GENERATED by tools/map_builder/build_osm_signals.py — do not edit.",
        f"// Source: {PBF.name}. Data (c) OpenStreetMap contributors, ODbL 1.0",
        "// (https://www.openstreetmap.org/copyright). highway=traffic_signals nodes,",
        f"// near-duplicates within {DEDUP_M:.0f} m removed. {len(keep)} points, "
        f"{sum(1 for k in keep if k[2] != 0xFFFF)} with a travel direction (traffic_signals:direction).",
        '#include "OsmTrafficSignals.h"',
        "",
        f"const int kOsmTrafficSignalCount = {len(keep)};",
        "const OsmSignalPoint kOsmTrafficSignals[] = {",
    ]
    for la, lo, dd in keep:
        lines.append(f"    {{{la}, {lo}, {dd}}},")
    lines += ["};", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{len(h.nodes)} nodes ({ndir} with direction) -> {len(keep)} signals -> {OUT} "
          f"({len(keep) * 12 / 1024:.0f} KB in flash)")


if __name__ == "__main__":
    main()
